export const GET_CLASSES_LOAD="GET_CLASSES_LOAD";
export const GET_CLASSES_SUCCESS="GET_CLASSES_SUCCESS";
export const GET_CLASSES_FAILED="GET_CLASSES_FAILED";
export const DELETE_CLASSE = "DELETE_CLASSE"; 
export const EDIT_CLASSE="EDIT_CLASSE";
export const GET_CLASSE="GET_CLASSE";
// POST
export const  POST_ETUDIANT="POST_ETUDIANT";
export const  POST_PROFFESEUR="POST_PROFFESEUR";

// remouve
export const  REMOUVE_ETUDIANT="REMOUVE_ETUDIANT";
export const  REMOUVE_PROFESSEUR="REMOUVE_PROFESSEUR";