export const LOAD_EMPLOYER = "LOAD_EMPLOYER";
export const FAIL_EMPLOYER = "FAIL_EMPLOYERS";
export const GET_EMPLOYERS_LOAD="GET_EMPLOYERS_LOAD";
export const GET_EMPLOYERS_SUCCESS="GET_EMPLOYERS_SUCCESS";
export const GET_EMPLOYERS_FAILED="GET_EMPLOYERS_FAILED";
export const DELETE_EMPLOYER= "DELETE_EMPLOYER";
export const EDIT_EMPLOYER="EDIT_EMPLOYER";
export const GET_EMPLOYER="GET_EMPLOYER";
