export const GET_EVENEMENTS_LOAD="GET_EVENEMENTS_LOAD";
export const GET_EVENEMENTS_SUCCESS="GET_EVENEMENTS_SUCCESS";
export const GET_EVENEMENTS_FAILED="GET_EVENEMENTS_FAILED";
export const DELETE_EVENEMENT = "DELETE_EVENEMENTS"; 
export const EDIT_EVENEMENT="EDIT_EVENEMENT";
export const GET_EVENEMENT="GET_EVENEMENT";

export const  PARTICIPE="PARTICIPE";
export const UNPARTICIPE="UNPARTICIPE";
